services:
  db:
    container_name: url_short_mongodb
    env_file: .env.example
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db
  url_short:
    container_name: url_short
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.example
    ports:
      - '3000:3000'
    volumes:
      - gems:/usr/local/bundle
      - .:/url_short

volumes:
  gems:
  mongodb:
